version: '3'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./envs/db.env
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    env_file:
      - ./envs/db.env
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    env_file:
      - ./envs/db.env
    ports:
      - "27017:27017"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  directus:
    image: directus/directus:latest
    container_name: directus
    env_file:
      - ./envs/db.env
    ports:
      - "8055:8055"
    depends_on:
      - postgres
      - redis
    volumes:
      - directus-data:/directus
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    depends_on:
      - nginx
  cadvisor:
    image: my-custom-cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - postgres
      - mongodb
      - redis
volumes:
  directus-data:
  redis-data:
  mongo-data:

networks:
  rentelektro-network:

