services:
  backend:
    build: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - envs/config.dev.env
      - envs/postgres.dev.env
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POETRY_VIRTUALENVS_CREATE=false
      - POETRY_VIRTUALENVS_IN_PROJECT=false
    volumes:
      - .:/app
      - /app/.venv
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - .pytest_cache/
            - .ruff_cache/
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: Dockerfile
    networks:
      - api-network
      - postgres-network
      - rentelektro-network

  postgres:
    image: postgres:17
    env_file:
      - envs/postgres.dev.env
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tests:
    build: .
    command: [ "sh", "-c", "sleep 5 && python -m pytest" ]
    env_file:
      - envs/config.dev.env
      - envs/postgres.dev.env
    environment:
      - POSTGRES_HOST=postgres
      - POETRY_VIRTUALENVS_CREATE=false
      - POETRY_VIRTUALENVS_IN_PROJECT=false
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - api-network
      - postgres-network

volumes:
  postgres-data:

networks:
  api-network:
    driver: bridge
  postgres-network:
    driver: bridge
  rentelektro-network:
    driver: bridge
