default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: backend-ruff-format
        name: backend ruff format check
        entry: poetry
        args: ["-C", "backend_rentelektro", "run", "ruff", "format", "--check", "."]
        language: system
        pass_filenames: false
        files: ^backend_rentelektro/
        stages: [pre-commit]

      - id: backend-ruff-check
        name: backend ruff lint
        entry: poetry
        args: ["-C", "backend_rentelektro", "run", "ruff", "check", "."]
        language: system
        pass_filenames: false
        files: ^backend_rentelektro/
        stages: [pre-commit]

      - id: backend-pytest
        name: backend pytest
        entry: poetry
        args: ["-C", "backend_rentelektro", "run", "pytest"]
        language: system
        pass_filenames: false
        files: ^backend_rentelektro/
        stages: [pre-push]
