export const TOOL_TYPE_OPTIONS = [
  { title: 'Wiertarka', value: 'drill' },
  { title: 'Wiertarko-wkrętarka', value: 'drill_driver' },
  { title: 'Szlifierka', value: 'grinder' },
  { title: 'Piła', value: 'saw' },
  { title: 'Młot', value: 'hammer' },
  { title: 'Młot udarowy', value: 'rotary_hammer' },
  { title: 'Wkrętarka', value: 'driver' },
  { title: 'Odkurzacz przemysłowy', value: 'industrial_vacuum' },
  { title: 'Kosiarka', value: 'mower' },
  { title: 'Podkaszarka', value: 'trimmer' },
  { title: 'Myjka ciśnieniowa', value: 'pressure_washer' },
  { title: 'Agregat prądotwórczy', value: 'generator' },
  { title: 'Spawarka', value: 'welder' },
  { title: 'Kompresor', value: 'compressor' },
  { title: 'Pilarka łańcuchowa', value: 'chainsaw' },
  { title: 'Pilarka tarczowa', value: 'circular_saw' },
  { title: 'Wyrzynarka', value: 'jigsaw' },
  { title: 'Zagęszczarka', value: 'compactor' },
  { title: 'Glebogryzarka', value: 'tiller' },
] as const;

export const TOOL_BRAND_OPTIONS = [
  { title: 'Bosch Professional', value: 'Bosch Professional' },
  { title: 'Makita', value: 'Makita' },
  { title: 'DeWalt', value: 'DeWalt' },
  { title: 'Milwaukee', value: 'Milwaukee' },
  { title: 'Hilti', value: 'Hilti' },
  { title: 'Stihl', value: 'Stihl' },
  { title: 'Kärcher', value: 'Kärcher' },
  { title: 'Honda', value: 'Honda' },
  { title: 'Husqvarna', value: 'Husqvarna' },
  { title: 'Einhell', value: 'Einhell' },
  { title: 'Metabo', value: 'Metabo' },
  { title: 'Yato', value: 'Yato' },
  { title: 'Dedra', value: 'Dedra' },
  { title: 'Ryobi', value: 'Ryobi' },
  { title: 'Black+Decker', value: 'Black+Decker' },
] as const;
