services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_PROXY_TARGET=http://nginx:80
    ports:
      - "8080:8080"
    restart: on-failure
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
