version: '3.9'
name: re_frontend
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: on-failure
    tty: true
    stdin_open: true
    command: npm run serve
    networks:
      - app-network
      - api-network
      - rentelektro-network

networks:
  app-network:
    driver: bridge

