services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_PROXY_TARGET=http://nginx:80
    ports:
      - "8080:8080"
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
