"""category repr

Revision ID: bb16fc5ef791
Revises: dfd6485a79b7
Create Date: 2026-04-29 10:46:21.985621
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'bb16fc5ef791'
down_revision = 'dfd6485a79b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('public_id', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_tools_public_id'), 'tools', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_public_id'), table_name='tools')
    op.drop_column('tools', 'public_id')
    # ### end Alembic commands ###
